let button = document.querySelector('#btn');
let area1 = document.querySelector('#area1');
let area2 = document.querySelector('#area2');
let data = {
    'A': 'ALT N6 N5',
    'B': 'ALT N6 N6',
    'C': 'ALT N6 N7',
    'D': 'ALT N6 N8',
    'E': 'ALT N6 N9',
    'F': 'ALT N7 N0',
    'G': 'ALT N7 N1',
    'H': 'ALT N7 N2',
    'I': 'ALT N7 N3',
    'J': 'ALT N7 N4',
    'K': 'ALT N7 N5',
    'L': 'ALT N7 N6',
    'M': 'ALT N7 N7',
    'N': 'ALT N7 N8',
    'O': 'ALT N7 N9',
    'P': 'ALT N8 N0',
    'Q': 'ALT N8 N1',
    'R': 'ALT N8 N2',
    'S': 'ALT N8 N3',
    'T': 'ALT N8 N4',
    'U': 'ALT N8 N5',
    'V': 'ALT N8 N6',
    'W': 'ALT N8 N7',
    'X': 'ALT N8 N8',
    'Y': 'ALT N8 N9',
    'Z': 'ALT N9 N0',
    'a': 'ALT N9 N7',
    'b': 'ALT N9 N8',
    'c': 'ALT N9 N9',
    'd': 'ALT N1 N0 N0',
    'e': 'ALT N1 N0 N1',
    'f': 'ALT N1 N0 N2',
    'g': 'ALT N1 N0 N3',
    'h': 'ALT N1 N0 N4',
    'i': 'ALT N1 N0 N5',
    'j': 'ALT N1 N0 N6',
    'k': 'ALT N1 N0 N7',
    'l': 'ALT N1 N0 N8',
    'm': 'ALT N1 N0 N9',
    'n': 'ALT N1 N1 N0',
    'o': 'ALT N1 N1 N1',
    'p': 'ALT N1 N1 N2',
    'q': 'ALT N1 N1 N3',
    'r': 'ALT N1 N1 N4',
    's': 'ALT N1 N1 N5',
    't': 'ALT N1 N1 N6',
    'u': 'ALT N1 N1 N7',
    'v': 'ALT N1 N1 N8',
    'w': 'ALT N1 N1 N9',
    'x': 'ALT N1 N2 N0',
    'y': 'ALT N1 N2 N1',
    'z': 'ALT N1 N2 N2',
    ',': 'ALT N4 N4',
    '.': 'ALT N4 N6',
    '/': 'ALT N4 N7',
    '\\': 'ALT N9 N2',
    '<': 'ALT N6 N0',
    '>': 'ALT N6 N2',
    '?': 'ALT N6 N3',
    ';': 'ALT N5 N9',
    ':': 'ALT N5 N8',
    '"': 'ALT N3 N4',
    '[': 'ALT N9 N1',
    ']': 'ALT N9 N3',
    '{': 'ALT N1 N2 N3',
    '}': 'ALT N1 N2 N5',
    ' ': 'ALT N3 N2',
    '!': 'ALT N3 N3',
    '@': 'ALT N6 N4',
    '#': 'ALT N3 N5',
    '№': 'ALT N2 N5 N2',
    '$': 'ALT N3 N6',
    '%': 'ALT N3 N7',
    '^': 'ALT N9 N4',
    '&': 'ALT N3 N8',
    '*': 'ALT N4 N2',
    '(': 'ALT N4 N0',
    ')': 'ALT N4 N1',
    '-': 'ALT N4 N5',
    '_': 'ALT N9 N5',
    '+': 'ALT N4 N3',
    '=': 'ALT N6 N1',
    "'": 'ALT N3 N9',
    '`': 'ALT N9 N6',
    '~': 'ALT N1 N2 N6',
    '0': 'ALT N4 N8',
    '1': 'ALT N4 N9',
    '2': 'ALT N5 N0',
    '3': 'ALT N5 N1',
    '4': 'ALT N5 N2',
    '5': 'ALT N5 N3',
    '6': 'ALT N5 N4',
    '7': 'ALT N5 N5',
    '8': 'ALT N5 N6',
    '9': 'ALT N5 N7',
    'А': 'ALT N1 N2 N8',
    'Б': 'ALT N1 N2 N9',
    'В': 'ALT N1 N3 N0',
    'Г': 'ALT N1 N3 N1',
    'Д': 'ALT N1 N3 N2',
    'Е': 'ALT N1 N3 N3',
    'Ж': 'ALT N1 N3 N4',
    'З': 'ALT N1 N3 N5',
    'И': 'ALT N1 N3 N6',
    'Й': 'ALT N1 N3 N7',
    'К': 'ALT N1 N3 N8',
    'Л': 'ALT N1 N3 N9',
    'М': 'ALT N1 N4 N0',
    'Н': 'ALT N1 N4 N1',
    'О': 'ALT N1 N4 N2',
    'П': 'ALT N1 N4 N3',
    'Р': 'ALT N1 N4 N4',
    'С': 'ALT N1 N4 N5',
    'Т': 'ALT N1 N4 N6',
    'У': 'ALT N1 N4 N7',
    'Ф': 'ALT N1 N4 N8',
    'Х': 'ALT N1 N4 N9',
    'Ц': 'ALT N1 N5 N0',
    'Ч': 'ALT N1 N5 N1',
    'Ш': 'ALT N1 N5 N2',
    'Щ': 'ALT N1 N5 N3',
    'Ъ': 'ALT N1 N5 N4',
    'Ы': 'ALT N1 N5 N5',
    'Ь': 'ALT N1 N5 N6',
    'Э': 'ALT N1 N5 N7',
    'Ю': 'ALT N1 N5 N8',
    'Я': 'ALT N1 N5 N9',
    'а': 'ALT N1 N6 N0',
    'б': 'ALT N1 N6 N1',
    'в': 'ALT N1 N6 N2',
    'г': 'ALT N1 N6 N3',
    'д': 'ALT N1 N6 N4',
    'е': 'ALT N1 N6 N6',
    'ж': 'ALT N1 N6 N6',
    'з': 'ALT N1 N6 N7',
    'и': 'ALT N1 N6 N8',
    'й': 'ALT N1 N6 N9',
    'к': 'ALT N1 N7 N0',
    'л': 'ALT N1 N7 N1',
    'м': 'ALT N1 N7 N2',
    'н': 'ALT N1 N7 N3',
    'о': 'ALT N1 N7 N4',
    'п': 'ALT N1 N7 N5',
    'р': 'ALT N2 N2 N4',
    'с': 'ALT N2 N2 N5',
    'т': 'ALT N2 N2 N6',
    'у': 'ALT N2 N2 N7',
    'ф': 'ALT N2 N2 N8',
    'х': 'ALT N2 N2 N9',
    'ц': 'ALT N2 N3 N0',
    'ч': 'ALT N2 N3 N1',
    'ш': 'ALT N2 N3 N2',
    'щ': 'ALT N2 N3 N3',
    'ъ': 'ALT N2 N3 N4',
    'ы': 'ALT N2 N3 N5',
    'ь': 'ALT N2 N3 N6',
    'э': 'ALT N2 N3 N7',
    'ю': 'ALT N2 N3 N8',
    'я': 'ALT N2 N3 N9'
  };
button.addEventListener('click', convert);

function convert(){
    area2.value = '';
    let key = area1.value;
    let proxy = new Proxy(data, {
        get(target, key){
            if (key in target){
                return target[key];
            }    
            else {
                return `Character ${key} does not apply to ALT-codes`;
            }
        }
    });   
    let arr = key.split('');
    for (let i = 0; i < arr.length; i++) {
        area2.value += proxy[arr[i]] + '\n';
    }
}
